### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by 0livrea1** [artyshko/smd#10]
I have this error:

`./main.py
  File "./main.py", line 71
    fixed_name = f'{info["artist"][0]} - {info["name"]}'
                                                       ^
SyntaxError: invalid syntax
`

**Comment by aledv** [comment]
I have the same issue on a raspberry pi. 
the same project, same folder to another pc and smd works fine. 

someone know what due that? 

thanks

**Comment by artyshko** [comment]
it must be **python3** (in my case - 3.6.7), but desktop version _isn't available_ at the moment

**Comment by aledv** [comment]
Yep, it is due to the Python version.

I have updated to Python3.6.5 and I don’t have this problem now.

**Comment by Msameim181** [comment]
i have this problem too.
i use Python 3.7.2 and it doesn't work.
what should i do ?

./main.py File "./main.py", line 71 fixed_name = f'{info["artist"][0]} - {info["name"]}' ^ SyntaxError: invalid syntax

thanks!

**Comment by Jesseslco** [comment]
>=3.6 should work

**Comment by ducho** [comment]
Not working for me too
```
iMac:smd Ducho$ ./main.py -sa "https://open.spotify.com/album/2xbzJIow0xg4zryI2hWgnX"
  File "./main.py", line 30
    notify.send(f'Downloading from YouTube', downloaded=False)
                                          ^
SyntaxError: invalid syntax
```

**Comment by ducho** [comment]
Donate? Why? 
```
iMac:smd Ducho$ ./main.py -sa "https://open.spotify.com/album/2xbzJIow0xg4zryI2hWgnX"
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
    from youtube import Youtube
  File "/Users/Ducho/Downloads/smd/youtube.py", line 16, in <module>
    from moviepy.editor import *
  File "/usr/local/lib/python3.7/site-packages/moviepy/editor.py", line 26, in <module>
    imageio.plugins.ffmpeg.download()
  File "/usr/local/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 73, in download
    force_download=force_download)
  File "/usr/local/lib/python3.7/site-packages/imageio/core/fetching.py", line 127, in get_remote_file
    _fetch_file(url, filename)
  File "/usr/local/lib/python3.7/site-packages/imageio/core/fetching.py", line 183, in _fetch_file
    os.path.basename(file_name))
OSError: Unable to download 'ffmpeg-osx-v3.2.4'. Perhaps there is a no internet connection? If there is, please report this problem.
```
