### ISSUE TITLE
No module named 'kernel.smdc.core'

### ISSUE THREAD

**Issue by MoliseMG** [artyshko/smd#100]
kernel smdc is empty

**Comment by IIxauII** [comment]
same

**Comment by IIxauII** [comment]
pi@pizerotester:~/spotify-ripper $ python3 main.py randomspotifyurl

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from kernel import controller
  File "/home/pi/spotify-ripper/kernel/controller.py", line 16, in <module>
    from kernel.smdc.core import CORE
ModuleNotFoundError: No module named 'kernel.smdc.core'
