### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by OTsector** [artyshko/smd#102]
```./main.py -ss "https://open.spotify.com/track/2QoDAlMnML5haTXvYRS86X?si=eMGX4dlwQd-7dyiG6OmUHQ"
Traceback (most recent call last):
  File "/tmp/smd/./main.py", line 3, in <module>
    from youtube import Youtube
  File "/tmp/smd/youtube.py", line 20, in <module>
    imageio.plugins.ffmpeg.download()
  File "/usr/local/lib/python3.9/dist-packages/imageio/plugins/ffmpeg.py", line 37, in download
    raise RuntimeError(
RuntimeError: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'
```

**Comment by khalidoy** [comment]
same issue

**Comment by khalidoy** [comment]
i think i ve figured it out 

The update of imageio causes this error.
Using the imageio on version 2.4.1 will solve your problem:

sudo pip3 install imageio==2.4.1

**Comment by denzven** [comment]
same problem didnt work
