### ISSUE TITLE
Not working smd

### ISSUE THREAD

**Issue by Jodi42-shb** [artyshko/smd#104]
sudo ./main.py -sp "_______"

 
Traceback (most recent call last):
  File "./main.py", line 2, in <module>
    from spotify import Spotify
  File "/opt/smd/spotify.py", line 3, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'

**Comment by kubabar** [comment]
install spotipy with pip

**Comment by Jodi42-shb** [comment]
There is no such package named pip in repos.

**Comment by kubabar** [comment]
well, if you don't know what pip is, maybe you shouldn't be using this program

type:
`pip install spotipy`

if your bash says "command not found", check whether you have even installed python to your PATH, by typing `which python` and if it says something, you can cd to it (without python) to check if you have pip there. if you don't reinstall python and make sure to tick the "add python to Path" box.
