### ISSUE TITLE
installation instructions not clear

### ISSUE THREAD

**Issue by thaynos** [artyshko/smd#108]
i tried following the rules in instructions.txt butt he chmod and sudo commands arent there on windows. i tried to open the .py commands but they dont work. its showing spotipy not downloaded. 
![image](https://user-images.githubusercontent.com/83282129/121666787-ae2f5f00-caba-11eb-9ffd-5983c222e2c2.png)
but as you see i have already installed spotipy. when trying to upgrade its showing this error
```
C:\Users\GUEST123>pip install spotipy --upgrade
Collecting spotipy
  Using cached spotipy-2.18.0-py3-none-any.whl (26 kB)
Collecting requests>=2.25.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting six>=1.15.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting urllib3>=1.26.0
  Using cached urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Installing collected packages: urllib3, idna, chardet, certifi, six, requests, spotipy
  WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'c:\\python39\\Scripts\\chardetect.exe' -> 'c:\\python39\\Scripts\\chardetect.exe.deleteme'

WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.
```
when installing the req.txt this is what happens
```
C:\Users\GUEST123\Downloads\smd-1.7.1\smd-1.7.1>pip3 install -r requirements.txt
Collecting notify2==0.3.1
  Downloading notify2-0.3.1-py2.py3-none-any.whl (8.0 kB)
Collecting spotipy==2.4.4
  Downloading spotipy-2.4.4.tar.gz (15 kB)
Collecting lyricsgenius==1.4.0
  Downloading lyricsgenius-1.4.0-py3-none-any.whl (13 kB)
Collecting lxml==4.3.3
  Downloading lxml-4.3.3.tar.gz (4.4 MB)
     |████████████████████████████████| 4.4 MB 328 kB/s
Collecting mutagen==1.41.0
  Downloading mutagen-1.41.0.tar.gz (918 kB)
     |████████████████████████████████| 918 kB 6.4 MB/s
Collecting requests==2.21.0
  Downloading requests-2.21.0-py2.py3-none-any.whl (57 kB)
     |████████████████████████████████| 57 kB 553 kB/s
Collecting moviepy==0.2.3.5
  Downloading moviepy-0.2.3.5.tar.gz (372 kB)
     |████████████████████████████████| 372 kB 3.3 MB/s
Collecting imageio==2.3.0
  Downloading imageio-2.3.0-py2.py3-none-any.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 2.2 MB/s
Collecting humanize==0.5.1
  Downloading humanize-0.5.1.tar.gz (14 kB)
Collecting pygame==1.9.6
  Downloading pygame-1.9.6.tar.gz (3.2 MB)
     |████████████████████████████████| 3.2 MB 3.3 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GUEST123\\AppData\\Local\\Temp\\pip-install-tix5d50_\\pygame_7efef4f40f944157ad42ece7b6f3bb66\\setup.py'"'"'; __file__='"'"'C:\\Users\\GUEST123\\AppData\\Local\\Temp\\pip-install-tix5d50_\\pygame_7efef4f40f944157ad42ece7b6f3bb66\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\GUEST123\AppData\Local\Temp\pip-pip-egg-info-4_p7gqj6'
         cwd: C:\Users\GUEST123\AppData\Local\Temp\pip-install-tix5d50_\pygame_7efef4f40f944157ad42ece7b6f3bb66\
    Complete output (17 lines):


    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using WINDOWS configuration...


    Download prebuilts to "prebuilt_downloads" and copy to "./prebuilt-x64"? [Y/n]Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\GUEST123\AppData\Local\Temp\pip-install-tix5d50_\pygame_7efef4f40f944157ad42ece7b6f3bb66\setup.py", line 194, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "C:\Users\GUEST123\AppData\Local\Temp\pip-install-tix5d50_\pygame_7efef4f40f944157ad42ece7b6f3bb66\buildconfig\config.py", line 210, in main
        deps = CFG.main(**kwds)
      File "C:\Users\GUEST123\AppData\Local\Temp\pip-install-tix5d50_\pygame_7efef4f40f944157ad42ece7b6f3bb66\buildconfig\config_win.py", line 576, in main
        and download_win_prebuilt.ask(**download_kwargs):
      File "C:\Users\GUEST123\AppData\Local\Temp\pip-install-tix5d50_\pygame_7efef4f40f944157ad42ece7b6f3bb66\buildconfig\download_win_prebuilt.py", line 302, in ask
        reply = raw_input(
    EOFError: EOF when reading a line
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/0f/9c/78626be04e193c0624842090fe5555b3805c050dfaa81c8094d6441db2be/pygame-1.9.6.tar.gz#sha256=301c6428c0880ecd4a9e3951b80e539c33863b6ff356a443db1758de4f297957 (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pygame==1.9.6 (from versions: 1.9.2rc1, 1.9.2, 1.9.3, 1.9.4.dev0, 1.9.4rc1, 1.9.4, 1.9.5rc1, 1.9.5rc2, 1.9.5, 1.9.6rc1, 1.9.6rc2, 1.9.6, 2.0.0.dev1, 2.0.0.dev2, 2.0.0.dev3, 2.0.0.dev4, 2.0.0.dev6, 2.0.0.dev8, 2.0.0.dev10, 2.0.0.dev12, 2.0.0.dev14, 2.0.0.dev16, 2.0.0.dev18, 2.0.0.dev20, 2.0.0.dev22, 2.0.0.dev24, 2.0.0, 2.0.1.dev1, 2.0.1)
ERROR: No matching distribution found for pygame==1.9.6
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.
```
when trying to update pip a windows pop up comes up showing that app cant run on your pc

**Comment by goshawk22** [comment]
I don't think this project works with Windows easily, probably best to try it on Linux.
Anyway it looks like this project is dead/inactive.

**Comment by thaynos** [comment]
ah damn
