### ISSUE TITLE
Everything installed fine. App freezes and quits on startup!

### ISSUE THREAD

**Issue by Suvam4549** [artyshko/smd#23]
My system info: Manjaro KDE 18.1.0
Everything is updated on the system.
I followed the instructions to install, all the requirements downloaded but failed to install saying that I don't have permission to install and I must use --user.
Then I executed:
```
pip3 install --user -r requirements.txt
pip3 install --user PyQtWebEngine
```
It all installed fine this time except I got one warning saying sth like beautifulsoup4 reqired ==4.6.0 & beautifulsoup4 installed : 4.8.0 (And it's incompatible in RED letters). Then I checked the requirements text myself and it apparently says 4.8.0 is required.. What is wrong here?

Since I am on Arch,` sudo apt-get install python3-pyqt5.qtwebengine ` didn't work for me.. So I went over to Arch repo and installed these two packages:
https://www.archlinux.org/packages/extra/x86_64/python-pyqtwebengine/
https://www.archlinux.org/packages/extra/x86_64/python-pyqt5/

After that, I executed 
```
chmod +x run.sh
./run.sh
```
And then I get that splash screen, it hangs, then it fades away after I launch. Please help!
Here it is: https://imgur.com/6Lz2ca6

**Comment by Suvam4549** [comment]
Just tried the CLI version as well.. 
```Welcome to fish, the friendly interactive shell
phook@manjaro ~> git clone https://github.com/artyshko/smd.git
fatal: destination path 'smd' already exists and is not an empty directory.
phook@manjaro ~> cd smd
phook@manjaro ~/smd> pip3 install -r requirements.txt
Requirement already satisfied: notify2==0.3.1 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (0.3.1)
Requirement already satisfied: spotipy==2.4.4 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2.4.4)
Requirement already satisfied: lyricsgenius==1.4.0 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (1.4.0)
Requirement already satisfied: lxml==4.3.3 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (4.3.3)
Requirement already satisfied: mutagen==1.41.0 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (1.41.0)
Requirement already satisfied: requests==2.21.0 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2.21.0)
Requirement already satisfied: moviepy==0.2.3.5 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (0.2.3.5)
Requirement already satisfied: imageio==2.3.0 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (2.3.0)
Requirement already satisfied: humanize==0.5.1 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (0.5.1)
Requirement already satisfied: pygame==1.9.6 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (1.9.6)
Requirement already satisfied: youtube_dl==2019.7.30 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (2019.7.30)
Requirement already satisfied: Flask==0.12.2 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (0.12.2)
Requirement already satisfied: pytube==9.5.1 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (9.5.1)
Requirement already satisfied: PyQt5==5.13.0 in /home/phook/.local/lib/python3.7/site-packages (from -r requirements.txt (line 14)) (5.13.0)
Requirement already satisfied: beautifulsoup4==4.8.0 in /usr/lib/python3.7/site-packages (from -r requirements.txt (line 15)) (4.8.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/phook/.local/lib/python3.7/site-packages (from requests==2.21.0->-r requirements.txt (line 6)) (1.24.3)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3.7/site-packages (from requests==2.21.0->-r requirements.txt (line 6)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.7/site-packages (from requests==2.21.0->-r requirements.txt (line 6)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/phook/.local/lib/python3.7/site-packages (from requests==2.21.0->-r requirements.txt (line 6)) (2019.9.11)
Requirement already satisfied: decorator<5.0,>=4.0.2 in /home/phook/.local/lib/python3.7/site-packages (from moviepy==0.2.3.5->-r requirements.txt (line 7)) (4.4.0)
Requirement already satisfied: tqdm<5.0,>=4.11.2 in /home/phook/.local/lib/python3.7/site-packages (from moviepy==0.2.3.5->-r requirements.txt (line 7)) (4.36.1)
Requirement already satisfied: numpy in /home/phook/.local/lib/python3.7/site-packages (from moviepy==0.2.3.5->-r requirements.txt (line 7)) (1.17.2)
Requirement already satisfied: pillow in /usr/lib/python3.7/site-packages (from imageio==2.3.0->-r requirements.txt (line 8)) (6.1.0)
Requirement already satisfied: itsdangerous>=0.21 in /home/phook/.local/lib/python3.7/site-packages (from Flask==0.12.2->-r requirements.txt (line 12)) (1.1.0)
Requirement already satisfied: Werkzeug>=0.7 in /home/phook/.local/lib/python3.7/site-packages (from Flask==0.12.2->-r requirements.txt (line 12)) (0.16.0)
Requirement already satisfied: click>=2.0 in /home/phook/.local/lib/python3.7/site-packages (from Flask==0.12.2->-r requirements.txt (line 12)) (7.0)
Requirement already satisfied: Jinja2>=2.4 in /home/phook/.local/lib/python3.7/site-packages (from Flask==0.12.2->-r requirements.txt (line 12)) (2.10.1)
Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in /home/phook/.local/lib/python3.7/site-packages (from PyQt5==5.13.0->-r requirements.txt (line 14)) (4.19.19)
Requirement already satisfied: soupsieve>=1.2 in /usr/lib/python3.7/site-packages (from beautifulsoup4==4.8.0->-r requirements.txt (line 15)) (1.9.3)
Requirement already satisfied: MarkupSafe>=0.23 in /home/phook/.local/lib/python3.7/site-packages (from Jinja2>=2.4->Flask==0.12.2->-r requirements.txt (line 12)) (1.1.1)
phook@manjaro ~/smd> python3 main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from youtube import Youtube
  File "/home/phook/smd/youtube.py", line 16, in <module>
    from moviepy.editor import *
  File "/home/phook/.local/lib/python3.7/site-packages/moviepy/editor.py", line 26, in <module>
    imageio.plugins.ffmpeg.download()
  File "/home/phook/.local/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 73, in download
    force_download=force_download)
  File "/home/phook/.local/lib/python3.7/site-packages/imageio/core/fetching.py", line 127, in get_remote_file
    _fetch_file(url, filename)
  File "/home/phook/.local/lib/python3.7/site-packages/imageio/core/fetching.py", line 183, in _fetch_file
    os.path.basename(file_name))
OSError: Unable to download 'ffmpeg-linux64-v3.3.1'. Perhaps there is a no internet connection? If there is, please report this problem.
phook@manjaro ~/smd> 
```
I can confirm my internet is up and running perfectly fine. Proof : https://imgur.com/KbNjN4o

**Comment by artyshko** [comment]
Common problem - https://github.com/artyshko/smd/issues/3

**Comment by gustawdaniel** [comment]
This is duplicate of https://github.com/artyshko/smd/issues/8

Solved by @noraisk:

```
wget https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg.linux64
mv ffmpeg.linux64 ~/.imageio/ffmpeg/ffmpeg-linux64-v3.3.1
```
