### ISSUE TITLE
ModuleNotFoundError: No module named 'spotipy'

### ISSUE THREAD

**Issue by AlphaE-CPU** [artyshko/smd#29]
![image](https://user-images.githubusercontent.com/56701609/67922246-9bd00e00-fb80-11e9-9cbd-5a5509d58b06.png)

**Comment by brianroach** [comment]
I'm getting the same error.

**Comment by artyshko** [comment]
Try this one `pip3 install spotipy`
Spotipy - https://github.com/plamere/spotipy

**Comment by AmazingBite** [comment]
I'm having the same error

```bash
# python3.6 main.py -sp "https://open.spotify.com/playlist/50ayC7avUY9cRgXvQ7ZmcX"

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from spotify import Spotify
  File "/var/www/html/smd/spotify.py", line 3, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
```
```bash
# pip3 install -r requirements.txt

Requirement already satisfied: notify2==0.3.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: spotipy==2.4.4 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: lyricsgenius==1.4.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: lxml==4.3.3 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: mutagen==1.41.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: requests==2.21.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: moviepy==0.2.3.5 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: imageio==2.3.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: humanize==0.5.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied: pygame==1.9.6 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied: youtube_dl==2019.7.30 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied: Flask==0.12.2 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied: pytube==9.5.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied: PyQt5==5.13.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied: beautifulsoup4==4.8.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests==2.21.0->-r requirements.txt (line 6))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests==2.21.0->-r requirements.txt (line 6))
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests==2.21.0->-r requirements.txt (line 6))
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests==2.21.0->-r requirements.txt (line 6))
Requirement already satisfied: decorator<5.0,>=4.0.2 in /usr/local/lib/python3.5/dist-packages (from moviepy==0.2.3.5->-r requirements.txt (line 7))
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from moviepy==0.2.3.5->-r requirements.txt (line 7))
Requirement already satisfied: tqdm<5.0,>=4.11.2 in /usr/local/lib/python3.5/dist-packages (from moviepy==0.2.3.5->-r requirements.txt (line 7))
Requirement already satisfied: pillow in /usr/local/lib/python3.5/dist-packages (from imageio==2.3.0->-r requirements.txt (line 8))
Requirement already satisfied: click>=2.0 in /usr/local/lib/python3.5/dist-packages (from Flask==0.12.2->-r requirements.txt (line 12))
Requirement already satisfied: Werkzeug>=0.7 in /usr/local/lib/python3.5/dist-packages (from Flask==0.12.2->-r requirements.txt (line 12))
Requirement already satisfied: itsdangerous>=0.21 in /usr/local/lib/python3.5/dist-packages (from Flask==0.12.2->-r requirements.txt (line 12))
Requirement already satisfied: Jinja2>=2.4 in /usr/lib/python3/dist-packages (from Flask==0.12.2->-r requirements.txt (line 12))
Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in /usr/local/lib/python3.5/dist-packages (from PyQt5==5.13.0->-r requirements.txt (line 14))
Requirement already satisfied: soupsieve>=1.2 in /usr/local/lib/python3.5/dist-packages (from beautifulsoup4==4.8.0->-r requirements.txt (line 15))
Requirement already satisfied: MarkupSafe in /usr/lib/python3/dist-packages (from Jinja2>=2.4->Flask==0.12.2->-r requirements.txt (line 12))
```

**Comment by AmazingBite** [comment]
Problem solved by installing everything again.

**Comment by TheOldGoldenFish** [comment]
The problem is caused when you don't install the requirements properly. just reinstall that and it will run
