### ISSUE TITLE
"imageio.ffmpeg.download() has been deprecated. "

### ISSUE THREAD

**Issue by jamespo** [artyshko/smd#3]
python3 main.py 
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from youtube import Youtube
  File "/home/james/Downloads/smd/youtube.py", line 13, in <module>
    from moviepy.editor import *
  File "/home/james/.virtualenvs/utils3/lib/python3.7/site-packages/moviepy/editor.py", line 26, in <module>
    imageio.plugins.ffmpeg.download()
  File "/home/james/.virtualenvs/utils3/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 40, in download
    "imageio.ffmpeg.download() has been deprecated. "
RuntimeError: imageio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead.'

**Comment by artyshko** [comment]
**try** `pip3 install imageio-ffmpeg`

**Comment by ParadoxicalNerd** [comment]
It still did not work for me, so I followed the instruction here https://superuser.com/questions/1402892/runtimeerror-imageio-ffmpeg-download-has-been-deprecated-use-pip-install-im

It now says even though there is internet connection:
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
    from youtube import Youtube
  File "/home/pankaj/Music/smd/smd/youtube.py", line 13, in <module>
    from moviepy.editor import *
  File "/home/pankaj/.local/lib/python3.6/site-packages/moviepy/editor.py", line 26, in <module>
    imageio.plugins.ffmpeg.download()
  File "/usr/local/lib/python3.6/dist-packages/imageio/plugins/ffmpeg.py", line 79, in download
    get_remote_file(fname=fname, directory=directory, force_download=force_download)
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/fetching.py", line 130, in get_remote_file
    _fetch_file(url, filename)
  File "/usr/local/lib/python3.6/dist-packages/imageio/core/fetching.py", line 189, in _fetch_file
    % os.path.basename(file_name)
OSError: Unable to download 'ffmpeg-linux64-v3.3.1'. Perhaps there is a no internet connection? If there is, please report this problem.

**Comment by jamespo** [comment]
You can manually download ffmpeg by starting python and entering these two commands

import imageio
imageio.plugins.ffmpeg.download()

**Comment by ParadoxicalNerd** [comment]
Nope, still dosen't work.

![image](https://user-images.githubusercontent.com/47481513/54101810-8a68a480-43eb-11e9-8de3-df8c6319590e.png)

**Comment by jamespo** [comment]
Works for me on python 3.7 on Fedora 29 (in a virtualenv)

I have installed imageio-ffmpeg as well however.

It creates ~/.imageio/ffmpeg/ffmpeg-linux64-v3.3.1

**Comment by kaletaa** [comment]
You can solve this by downgrading imageio
`pip install imageio==2.4.1`

https://superuser.com/questions/1402892/runtimeerror-imageio-ffmpeg-download-has-been-deprecated-use-pip-install-im

**Comment by hans0v0** [comment]
sudo  apt install ffmpeg
pip3 install imageio-ffmpeg

**Comment by pawllo01** [comment]
New error appeared:
![new](https://user-images.githubusercontent.com/53797804/63724445-02227280-c858-11e9-809c-e76f3d4e3e0d.png)

**Comment by Jesseslco** [comment]
try manually install the ffmpeg

try this in python3 terminal:
```
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import imageio
>>> imageio.plugins.ffmpeg.download()
```

**Comment by gustawdaniel** [comment]
Because of 

+ https://github.com/artyshko/smd/issues/23
+ https://github.com/artyshko/smd/issues/8

seems to be related with this I propose to close them and add instruction of installing `ffmpeg.linux64` to README

**Comment by c0h2r** [comment]
Weirdly enough, the issue in my case solved itself after using `./main.py -ss "link_to_track"` (at least after doing `pip install imageio-ffmpeg`).

**Comment by joelwebb** [comment]
in google colab I had the same issue when trying to import this:
``` from moviepy.editor import VideoFileClip ```

 then did 

```!pip install imageio==2.4.0``` and then restarted the kernal, and it worked for me.
