### ISSUE TITLE
How this software is related to youtube-dl and ritiek/spotify-downloader

### ISSUE THREAD

**Issue by gustawdaniel** [artyshko/smd#34]
I found similar software like:

https://github.com/ritiek/spotify-downloader

I would ask about history of this repository. It is fork of other repository, or `https://github.com/ritiek/spotify-downloader` was inspired by this one or there are independent projects?

I have error:

```
Traceback (most recent call last):
  File "/home/daniel/.local/lib/python3.6/site-packages/mutagen/_util.py", line 235, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'cache/2VKiFacCGkfognvneCJC9S/2VKiFacCGkfognvneCJC9S.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 771, in <module>
    CLI.main(sys.argv[1:])
  File "./main.py", line 614, in main
    md.downloadBySpotifyUriAlbumMode(array[i+1], CLI.path)
  File "./main.py", line 282, in downloadBySpotifyUriAlbumMode
    data=info
  File "/home/daniel/pro/smd/editor.py", line 67, in setTags
    ID3=ID3
  File "/home/daniel/.local/lib/python3.6/site-packages/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "/home/daniel/.local/lib/python3.6/site-packages/mutagen/_util.py", line 139, in wrapper
    writable, create) as h:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/daniel/.local/lib/python3.6/site-packages/mutagen/_util.py", line 256, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'cache/2VKiFacCGkfognvneCJC9S/2VKiFacCGkfognvneCJC9S.mp3'
```

that was described in 

https://github.com/ritiek/spotify-downloader/issues/149

And instalation of

```
pip3 install spotdl -U
```

helped with this issue.

**Comment by adironco** [comment]
I didn't check the exact relation with https://github.com/ritiek/spotify-downloader, but `youtube_dl` seems to be used for the actual download part.

Indeed, every track is downloaded from Youtube as in `spotdl`. Spotify seems to be only used to get necessary track info. You can easily realize it since for some tracks Youtube versions are different and this programs gets such versions instead of Spotify ones, and code inspection confirms it. In other cases the correct Youtube video is not found and other random tracks are downloaded instead.

All legit, but quite misleading IMHO. It should be clearly stated in the project description.
