### ISSUE TITLE
OSError: Unable to download ffmpeg-osx-v3.2.4

### ISSUE THREAD

**Issue by ducho** [artyshko/smd#49]
Donate? Why? 

**OSError: Unable to download 'ffmpeg-osx-v3.2.4'. Perhaps there is a no internet connection? If there is, please report this problem.**

```
iMac:smd Ducho$ ./main.py -sa "https://open.spotify.com/album/2xbzJIow0xg4zryI2hWgnX"
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
    from youtube import Youtube
  File "/Users/Ducho/Downloads/smd/youtube.py", line 16, in <module>
    from moviepy.editor import *
  File "/usr/local/lib/python3.7/site-packages/moviepy/editor.py", line 26, in <module>
    imageio.plugins.ffmpeg.download()
  File "/usr/local/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 73, in download
    force_download=force_download)
  File "/usr/local/lib/python3.7/site-packages/imageio/core/fetching.py", line 127, in get_remote_file
    _fetch_file(url, filename)
  File "/usr/local/lib/python3.7/site-packages/imageio/core/fetching.py", line 183, in _fetch_file
    os.path.basename(file_name))
OSError: Unable to download 'ffmpeg-osx-v3.2.4'. Perhaps there is a no internet connection? If there is, please report this problem.
```

**Comment by mixj93** [comment]
same problem

**Comment by FRules** [comment]
same

**Comment by okandeb** [comment]
`pip3 install dbus-python`
and try again.

**Comment by jaindu** [comment]
I got the same error for windows then I used `pip3 install dbus-python` but then this error msg received(not a valid win 32 application) my os is 32bit
![image](https://user-images.githubusercontent.com/56291344/78349611-7fb61a00-75c1-11ea-9e61-fe187cb1fbb2.png)

**Comment by jaindu** [comment]
> `pip3 install dbus-python`
> and try again.

what should I use for windows

**Comment by TheOldGoldenFish** [comment]
https://github.com/artyshko/smd/issues/62#issuecomment-636327711
it may do the trick
