### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by ash-21** [artyshko/smd#52]
I was trying to download a playlist. After giving access of my spotify this error code is showing,

```
Traceback (most recent call last):
  File "./main.py", line 771, in <module>
    CLI.main(sys.argv[1:])
  File "./main.py", line 624, in main
    md.downloadBySpotifyUriPlaylistMode(array[i+1], CLI.path)
  File "./main.py", line 208, in downloadBySpotifyUriPlaylistMode
    playlist = user.getPlaylistTracks(playlist_uri)
  File "/home/ashraf/smd/spotify.py", line 153, in getPlaylistTracks
    for j, item in enumerate(playlist['items']):
KeyError: 'items'
```

And this when I tried to download a track,

```
ERROR: This video is unavailable.
2020-03-15 21:00:13,468 - ERROR - Some problems on classify loop
ERROR: This video is unavailable.
2020-03-15 21:00:16,342 - ERROR - Some problems on classify loop
ERROR: This video is unavailable.
2020-03-15 21:00:19,073 - ERROR - Some problems on classify loop
ERROR: This video is unavailable.
2020-03-15 21:00:22,153 - ERROR - Some problems on classify loop
ERROR: This video is unavailable.
```

**I am using Ubuntu 18.04 on Windows 10.**

**Comment by Eslsamu** [comment]
Same problem here on Ubuntu 18.04. Could be a problem with the spotify servers due to the crisis.
Because I also had problem logging into their website.

**Comment by pedroleon99** [comment]
1st error is probably because you're using a wrong link, maybe using Spotify desktop app(?). It gave me a longer link too and that error, fixed copying the playlist url from web player.
About 2nd one, try sudo pip install -U youtube-dl . Worked for me

**Comment by Eslsamu** [comment]
That fixed it, thanks !
