### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mahbod4782** [artyshko/smd#56]
![image](https://user-images.githubusercontent.com/17749373/79051731-1aa89700-7c47-11ea-9faa-5b2b5fa0f9b6.png)

**Comment by RedstoneFireBE** [comment]
In order to bypass this error, I have edited the line 160 in spotify.py

'image' : data['album']['images'][0]['url'] if len(data['album']['images']) > 0 else ''

It's seem to work fine

**Comment by savorocks** [comment]
I have a similar error when trying to download album from spotify, not sure how this causes the error in youtube.py:
```
python3 main.py -sa https://open.spotify.com/album/4EYZaRvd05NA1IVzJZv8dd
Downloading 1 of 12
Traceback (most recent call last):
  File "main.py", line 771, in <module>
    CLI.main(sys.argv[1:])
  File "main.py", line 614, in main
    md.downloadBySpotifyUriAlbumMode(array[i+1], CLI.path)
  File "main.py", line 279, in downloadBySpotifyUriAlbumMode
    self.__downloadMusicFromYoutube(fixed_name, info['uri'], info['duration_ms'])
  File "main.py", line 34, in __downloadMusicFromYoutube
    url=self.__youtube.getResult(),
  File "/home/savo/smd/youtube.py", line 70, in getResult
    return self.__result[i]
IndexError: list index out of range

```

**Comment by genialkartik** [comment]
Tried the hack by @RedstoneFireBE , but still getting the same error. 
Does anyone know any other trick?

**Comment by fullerspectrum** [comment]
> I have a similar error when trying to download album from spotify, not sure how this causes the error in youtube.py:
> 
> ```
> python3 main.py -sa "https://open.spotify.com/album/4EYZaRvd05NA1IVzJZv8dd"
> Downloading 1 of 12
> Traceback (most recent call last):
>   File "main.py", line 771, in <module>
>     CLI.main(sys.argv[1:])
>   File "main.py", line 614, in main
>     md.downloadBySpotifyUriAlbumMode(array[i+1], CLI.path)
>   File "main.py", line 279, in downloadBySpotifyUriAlbumMode
>     self.__downloadMusicFromYoutube(fixed_name, info['uri'], info['duration_ms'])
>   File "main.py", line 34, in __downloadMusicFromYoutube
>     url=self.__youtube.getResult(),
>   File "/home/savo/smd/youtube.py", line 70, in getResult
>     return self.__result[i]
> IndexError: list index out of range
> ```

Spotify is only used to find song/playlist info lol. Same with everything else I think.
It downloads from YT.


> Tried the hack by @RedstoneFireBE , but still getting the same error.
> Does anyone know any other trick?

The way it searches is dead, I think. Search results are loaded through JS now. Looks like just using the API (or the unofficial YTMusic one) would work, especially for just getting a URL.
