### ISSUE TITLE
I can't download any song or playlist

### ISSUE THREAD

**Issue by manujose94** [artyshko/smd#59]
I have already try to copy Spotify URL via web page and application and also I have made a second attempt with Deezer but without success.

Here output:

```
manu@manu-GS60-6QE:~/Music/smd$ ./main.py -dp "https://www.deezer.com/playlist/5852955582?utm_source=deezer&utm_content=playlist-5852955582&utm_term=1409000942_1587411805&utm_medium=web"
Downloading 1 of 50
ERROR: This video is unavailable.
2020-04-20 21:44:11,494 - ERROR - Some problems on classify loop
ERROR: This video is unavailable.
2020-04-20 21:44:13,276 - ERROR - Some problems on classify loop
ERROR: This video is unavailable.
2020-04-20 21:44:14,993 - ERROR - Some problems on classify loop
ERROR: This video is unavailable.
2020-04-20 21:44:16,578 - ERROR - Some problems on classify loop
ERROR: This video is unavailable.
Traceback (most recent call last):
  File "/home/manu/.local/lib/python3.7/site-packages/mutagen/_util.py", line 235, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'cache/D64786125T/D64786125T.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 771, in <module>
    CLI.main(sys.argv[1:])
  File "./main.py", line 654, in main
    md.downloadByDeezerUrlPlaylistMode(array[i+1], CLI.path)
  File "./main.py", line 441, in downloadByDeezerUrlPlaylistMode
    data=info
  File "/home/manu/Music/smd/editor.py", line 67, in setTags
    ID3=ID3
  File "/home/manu/.local/lib/python3.7/site-packages/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "/home/manu/.local/lib/python3.7/site-packages/mutagen/_util.py", line 139, in wrapper
    writable, create) as h:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/manu/.local/lib/python3.7/site-packages/mutagen/_util.py", line 256, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'cache/D64786125T/D64786125T.mp3'

```

thanks in advance

**Comment by TheOldGoldenFish** [comment]
Try a VPN and check if it works
