### ISSUE TITLE
ModuleNotFoundError: No module named 'dbus'

### ISSUE THREAD

**Issue by giannipi** [artyshko/smd#60]
When I use
python3 main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import notify2
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/notify2.py", line 39, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

**Comment by giannipi** [comment]
when I use
brew install dbus
Warning: dbus 1.12.16 is already installed and up-to-date
To reinstall 1.12.16, run `brew reinstall dbus`

**Comment by nero01** [comment]
Same issue, here did you solve it?

**Comment by giannipi** [comment]
no :(

**Comment by macoune** [comment]
You have to execute `pip3 install dbus-python` after `brew install dbus` and it should work

**Comment by diegoquintanav** [comment]
For those landing here randomly


```
sudo apt install build-essential libdbus-glib-1-dev libgirepository1.0-dev
pip install dbus-python
```

worked on mint 21.1

[source](https://stackoverflow.com/a/62510708/5819113)
