### ISSUE TITLE
Unable to import modules

### ISSUE THREAD

**Issue by soufianefariss** [artyshko/smd#7]
After successfully installing all the requirements, I am not able to run the script `./main.py`:

> Traceback (most recent call last):
  File "./main.py", line 3, in <module>
    from youtube import Youtube
  File "/home/fariss/smd/youtube.py", line 13, in <module>
    from moviepy.editor import *
  File "/home/fariss/.local/lib/python3.6/site-packages/moviepy/editor.py", line 23, in <module>
    import imageio
  File "/home/fariss/.local/lib/python3.6/site-packages/imageio/__init__.py", line 22, in <module>
    from .core import FormatManager, RETURN_BYTES
  File "/home/fariss/.local/lib/python3.6/site-packages/imageio/core/__init__.py", line 10, in <module>
    from .util import Image, Array, Dict, asarray, image_as_uint, urlopen
  File "/home/fariss/.local/lib/python3.6/site-packages/imageio/core/util.py", line 27, in <module>
    import numpy as np
  File "/home/fariss/.local/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/fariss/.local/lib/python3.6/site-packages/numpy/core/__init__.py", line 91, in <module>
    raise ImportError(msg.format(path))
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/home/fariss/.local/lib/python3.6/site-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.

I also don't know what packages to install manually.

**Comment by kaletaa** [comment]
Have you tried uninstalling all numpy instances like the error says?

**Comment by soufianefariss** [comment]
Hi @kaletaa,
I did just that. It got rid of the `numpy` error. However, I am still not able to run the script, here's the output: 

```console
fariss@fariss:~$ ./main.py
Traceback (most recent call last):
  File "./main.py", line 3, in <module>
    from youtube import Youtube
  File "/home/fariss/smd/youtube.py", line 13, in <module>
    from moviepy.editor import *
  File "/home/fariss/.local/lib/python3.6/site-packages/moviepy/editor.py", line 26, in <module>
    imageio.plugins.ffmpeg.download()
  File "/home/fariss/.local/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 79, in download
    get_remote_file(fname=fname, directory=directory, force_download=force_download)
  File "/home/fariss/.local/lib/python3.6/site-packages/imageio/core/fetching.py", line 130, in get_remote_file
    _fetch_file(url, filename)
  File "/home/fariss/.local/lib/python3.6/site-packages/imageio/core/fetching.py", line 189, in _fetch_file
    % os.path.basename(file_name)
OSError: Unable to download 'ffmpeg-linux64-v3.3.1'. Perhaps there is a no internet connection? If there is, please report this problem.
```

So, I tried installing 'ffmpeg-linux64-v3.3.1' manually, and I am getting this:

```console
fariss@fariss:~$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import imageio
>>> imageio.plugins.ffmpeg.download()
Imageio: 'ffmpeg-linux64-v3.3.1' was not found on your computer; downloading it now.
Try 1. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-linux64-v3.3.1 (43.8 MB)
Downloading: 23339008/45929032 bytes (50.8%)Error while fetching file: The read operation timed out.
Try 2. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-linux64-v3.3.1 (43.8 MB)
Downloading: 7340032/45929032 bytes (16.0%)Error while fetching file: The read operation timed out.
Try 3. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-linux64-v3.3.1 (43.8 MB)
Downloading: 3907584/45929032 bytes (8.5%)Error while fetching file: The read operation timed out.
Try 4. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-linux64-v3.3.1 (43.8 MB)
Downloading: 1032192/45929032 bytes (2.2%)Error while fetching file: The read operation timed out.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fariss/.local/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 79, in download
    get_remote_file(fname=fname, directory=directory, force_download=force_download)
  File "/home/fariss/.local/lib/python3.6/site-packages/imageio/core/fetching.py", line 130, in get_remote_file
    _fetch_file(url, filename)
  File "/home/fariss/.local/lib/python3.6/site-packages/imageio/core/fetching.py", line 189, in _fetch_file
    % os.path.basename(file_name)
OSError: Unable to download 'ffmpeg-linux64-v3.3.1'. Perhaps there is a no internet connection? If there is, please report this problem.
>>> 
>>> imageio.plugins.ffmpeg.download()
Imageio: 'ffmpeg-linux64-v3.3.1' was not found on your computer; downloading it now.
Try 1. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-linux64-v3.3.1 (43.8 MB)
Downloading: 25337856/45929032 bytes (55.2%)Error while fetching file: The read operation timed out.
Try 2. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-linux64-v3.3.1 (43.8 MB)
Downloading: 17154048/45929032 bytes (37.3%)Error while fetching file: The read operation timed out.
Try 3. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-linux64-v3.3.1 (43.8 MB)
Downloading: 32776192/45929032 bytes (71.4%)Error while fetching file: The read operation timed out.
Try 4. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-linux64-v3.3.1 (43.8 MB)
Downloading: 4505600/45929032 bytes (9.8%)Error while fetching file: The read operation timed out.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fariss/.local/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 79, in download
    get_remote_file(fname=fname, directory=directory, force_download=force_download)
  File "/home/fariss/.local/lib/python3.6/site-packages/imageio/core/fetching.py", line 130, in get_remote_file
    _fetch_file(url, filename)
  File "/home/fariss/.local/lib/python3.6/site-packages/imageio/core/fetching.py", line 189, in _fetch_file
    % os.path.basename(file_name)
OSError: Unable to download 'ffmpeg-linux64-v3.3.1'. Perhaps there is a no internet connection? If there is, please report this problem.
```

**Comment by kaletaa** [comment]
It can't see the ffmpeg binary, yeah. I'm trying to fix this bug too, I've opened another issue in this repo about it ( #8 )

**Comment by soufianefariss** [comment]
Problem fixed. Thanks.

**Comment by soufianefariss** [comment]
Closed issue.
