### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by computerdude100** [artyshko/smd#77]
No matter the request (tested on Spotify link and query, YouTube links are OK), this appears and fails every download: 

`computerdude100@P35-DS3R:~/smd$ python3 main.py -q "One - Metallica"
Traceback (most recent call last):
  File "main.py", line 771, in <module>
    CLI.main(sys.argv[1:])
  File "main.py", line 726, in main
    state, data = md.downloadBySearchQuery(query=array[i+1], path=CLI.path)
  File "main.py", line 143, in downloadBySearchQuery
    self.__downloadMusicFromYoutube(fixed_name, info['uri'], info['duration_ms'])
  File "main.py", line 34, in __downloadMusicFromYoutube
    url=self.__youtube.getResult(),
  File "/home/computerdude100/smd/youtube.py", line 68, in getResult
    return self.__result[i]
IndexError: list index out of range
`

Using a link or URI instead (can be song album or playlist):

`computerdude100@P35-DS3R:~/smd$` python3 main.py -ss "spotify:track:0P8qiUt6Of1XGHShZzvURU"
Traceback (most recent call last):
  File "main.py", line 771, in <module>
    CLI.main(sys.argv[1:])
  File "main.py", line 603, in main
    state = md.downloadBySpotifyUri(array[i+1], CLI.path)
  File "main.py", line 86, in downloadBySpotifyUri
    if self.__downloadMusicFromYoutube(fixed_name, info['uri'], info['duration_ms']):
  File "main.py", line 34, in __downloadMusicFromYoutube
    url=self.__youtube.getResult(),
  File "/home/computerdude100/smd/youtube.py", line 68, in getResult
    return self.__result[i]
IndexError: list index out of range
`

**Comment by dotiful** [comment]
confirm this issue

**Comment by yunooooo** [comment]
Also can confirm

**Comment by mmohamedyaser** [comment]
confirm this issue

**Comment by francescoMpro** [comment]
Same problem here. Has anyone fixed it?

**Comment by ali-oem** [comment]
Same here, any workaround ?

**Comment by noahbroyles** [comment]
I get the same problem.
