### ISSUE TITLE
it wont let me download anything.

### ISSUE THREAD

**Issue by k4lp** [artyshko/smd#85]
SO i tried downloading spotify playlist and this error was thrown:

`Traceback (most recent call last):
  File "main.py", line 771, in <module>
    CLI.main(sys.argv[1:])
  File "main.py", line 624, in main
    md.downloadBySpotifyUriPlaylistMode(array[i+1], CLI.path)
  File "main.py", line 208, in downloadBySpotifyUriPlaylistMode
    playlist = user.getPlaylistTracks(playlist_uri)
  File "/home/kalp/smd/spotify.py", line 153, in getPlaylistTracks
    for j, item in enumerate(playlist['items']):
KeyError: 'items'
`

**Comment by RafiSadad** [comment]
same`Traceback (most recent call last):
  File "./main.py", line 2, in <module>
    from spotify import Spotify
  File "/home/sadad/smd-master/spotify.py", line 3, in <module>
    import spotipy
ModuleNotFoundError: No module named 'spotipy'
root@sadad-LinuxMint:/home/sadad/smd-master# 
` i just got this

**Comment by Diegus83** [comment]
Did you install the requirements? Because it says it can’t find the “spotipy” module and that should have been installed during the Install requirements step.

**Comment by miraclx** [comment]
Check out freyr..https://github.com/miraclx/freyr-js

See #101

**Comment by 4qx** [comment]
freyr is pulling stuff off youtube. clspotify (zspotify) is what's up.

**Comment by miraclx** [comment]
[clspotify](https://github.com/agent255/clspotify) 💯.. love it for ripping straight off Spotify, however you always need a premium account.

[freyr](https://github.com/miraclx/freyr-js) instead, just tailors to everyone, regardless of whether they even have an account to begin with.

Now, `freyr` already has the ability to choose download sources (`-D, --downloader`). Just that, as of the time of writing, it only supports YouTube / YouTube Music. I'll make a note to extend that list to support optionally sourcing directly from Spotify / Deezer.

Thanks for bringing [clspotify](https://github.com/agent255/clspotify) to my attention, btw.

**Comment by 4qx** [comment]
> [clspotify](https://github.com/agent255/clspotify) 100.. love it for ripping straight off Spotify, however you always need a premium account.

Wrong. Free account works just fine, it has been working since I discovered it last week and it's working now.

> [freyr](https://github.com/miraclx/freyr-js) instead, just tailors to everyone, regardless of whether they even have an account to begin with.

freyr is an idiot-aimed youtube-dl clone of which there are dime a dozen, namely [spotify-downloader](https://github.com/spotDL/spotify-downloader), [spotify-dl](https://github.com/SathyaBhat/spotify-dl) and [Spotify-Playlist-Downloader](https://github.com/Collin-Varisco/Spotify-Playlist-Downloader). It does not work if a track is not available on youtube and the audio quality it is able to download is inferior to clspotify/zspotify. The biggest difference between freyr and others is that freyr has a misleading description on its main page and it author bears delusions of it being a wonderful project that warrants a pateron page.

**Comment by 4qx** [comment]
> [clspotify](https://github.com/agent255/clspotify) 100.. love it for ripping straight off Spotify, however you always need a premium account.

Wrong, having free account is sufficient for downloading. It has been working since I discovered it last week and it is working now.

> [freyr](https://github.com/miraclx/freyr-js) instead, just tailors to everyone, regardless of whether they even have an account to begin with.

freyr is a spotify-information-relying youtube-dl clone of which there are dime a dozen, namely [spotify-downloader](https://github.com/spotDL/spotify-downloader), [spotify-dl](https://github.com/SathyaBhat/spotify-dl) and [Spotify-Playlist-Downloader](https://github.com/Collin-Varisco/Spotify-Playlist-Downloader). The biggest difference between freyr and others is that freyr has a misleading description on its main page and its creator bears delusions of it being a wonderful project that warrants donation pages. It does not work if a track is not available on youtube and the audio quality it produces is inferior to the kind accessible on youtube or spotify even with a free account due to it re-encoding audio files that are already lossy. Not only that, it artificially inflates the size of the files by transcoding them to an unnecessarily higher 320k bitrate.
