### ISSUE TITLE
When I open the GUI version this appears

### ISSUE THREAD

**Issue by BendeckDavid** [artyshko/smd#89]
jinja2.exceptions.UndefinedError
jinja2.exceptions.UndefinedError: list object has no element 0

Traceback (most recent call last)
File "/home/david/.local/lib/python3.8/site-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/home/david/.local/lib/python3.8/site-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/home/david/.local/lib/python3.8/site-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/david/.local/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/home/david/.local/lib/python3.8/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/home/david/.local/lib/python3.8/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/david/.local/lib/python3.8/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/david/.local/lib/python3.8/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/home/david/.local/lib/python3.8/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/home/david/.local/lib/python3.8/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/david/Apps/SpotifyMusic/GUI/backend.py", line 34, in index
return render_template(
File "/home/david/.local/lib/python3.8/site-packages/flask/templating.py", line 133, in render_template
return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
File "/home/david/.local/lib/python3.8/site-packages/flask/templating.py", line 116, in _render
rv = template.render(context)
File "/home/david/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
self.environment.handle_exception()
File "/home/david/.local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
reraise(*rewrite_traceback_stack(source=source))
File "/home/david/.local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
raise value.with_traceback(tb)
File "/home/david/Apps/SpotifyMusic/GUI/templates/home.html", line 1, in top-level template code
{% extends 'base.html' %}
File "/home/david/Apps/SpotifyMusic/GUI/templates/base.html", line 98, in top-level template code
{% block body %}
File "/home/david/Apps/SpotifyMusic/GUI/templates/home.html", line 84, in block "body"
<div class="image-shadow-conc-r" style="background-image:url({{user_top_tracks[0].alb_image}});"></div>
File "/home/david/.local/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: list object has no element 0
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by spencerthayer** [comment]
Same.
