### ISSUE TITLE
[HELP] Unable to download 'ffmpeg-linux64-v3.3.1'.

### ISSUE THREAD

**Issue by mugi789** [artyshko/smd#90]
localdisk@ubuntu: /Git/smd$ ./main.py -ss "https://open.spotify.com/album/7vfTi5XtNwhkDNUCBK6xZK?si=xsLSSAEBRhyf3UBfSeudQw"Traceback (most recent call last):
  File "./main.py", line 3, in <module>
    from youtube import Youtube
  File "/home/localdisk/Git/smd/youtube.py", line 16, in <module>
    from moviepy.editor import *
  File "/home/localdisk/.local/lib/python3.6/site-packages/moviepy/editor.py", line 26, in <module>
    imageio.plugins.ffmpeg.download()
  File "/home/localdisk/.local/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 73, in download
    force_download=force_download)
  File "/home/localdisk/.local/lib/python3.6/site-packages/imageio/core/fetching.py", line 127, in get_remote_file
    _fetch_file(url, filename)
  File "/home/localdisk/.local/lib/python3.6/site-packages/imageio/core/fetching.py", line 183, in _fetch_file
    os.path.basename(file_name))
OSError: Unable to download 'ffmpeg-linux64-v3.3.1'. Perhaps there is a no internet connection? If there is, please report this problem.
localdisk@ubuntu: /Git/smd$

**`Tested on Ubuntu 18.04`**

**Comment by JBamberger** [comment]
You can open a python interpreter and run
```python
import imageio
imageio.plugins.ffmpeg.download()
```
This will download the file and thus resolve the error.

**Comment by iMonZ** [comment]
Same issue

**Comment by MarksenDE** [comment]
Same here

**Comment by Grrb** [comment]
running the same with:
FFMPEG_BINARY=/usr/local/bin/ffmpeg
(or perhaps where your ffmpeg is), worked for me: it started downloading the needed ffmpeg to my .imageio/ffmpeg/ dir.
