### ISSUE TITLE
[ERROR] No module named kernel.smdc.core while running on macOS

### ISSUE THREAD

**Issue by akshaybaweja** [artyshko/smd#94]
```
python3 main.py "https://open.spotify.com/track/4SlCYFaUQ8GRuwdpgniaGF\?si\=lrvOfSkSSqeV1LwKV3_17g"
Traceback (most recent call last):
  File "/Users/akshaybaweja/Downloads/smd-dev_ea-0/main.py", line 1, in <module>
    from kernel import controller
  File "/Users/akshaybaweja/Downloads/smd-dev_ea-0/kernel/controller.py", line 16, in <module>
    from kernel.smdc.core import CORE
ModuleNotFoundError: No module named 'kernel.smdc.core'
```

Can anybody help me with this?

**Comment by anirbanpolvolt** [comment]
Yes i also couldnt find the fix for it.
