### ISSUE TITLE
Issue while installing

### ISSUE THREAD

**Issue by 2ale2** [artyshko/smd#97]
After typing pip3 install -r requirements.txt the cmd shows progress in installation until this red error is shown:

```
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\myname\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\myname\\AppData\\Local\\Temp\\pip-install-qbgs41e9\\pygame_72a6d9dc72194e4f8f70c862493b94ad\\setup.py'"'"'; __file__='"'"'C:\\Users\\myname\\AppData\\Local\\Temp\\pip-install-qbgs41e9\\pygame_72a6d9dc72194e4f8f70c862493b94ad\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\myname\AppData\Local\Temp\pip-pip-egg-info-1nhv5533'
         cwd: C:\Users\myname\AppData\Local\Temp\pip-install-qbgs41e9\pygame_72a6d9dc72194e4f8f70c862493b94ad\
    Complete output (17 lines):


    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using WINDOWS configuration...


    Download prebuilts to "prebuilt_downloads" and copy to "./prebuilt-x64"? [Y/n]Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\myname\AppData\Local\Temp\pip-install-qbgs41e9\pygame_72a6d9dc72194e4f8f70c862493b94ad\setup.py", line 194, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "C:\Users\myname\AppData\Local\Temp\pip-install-qbgs41e9\pygame_72a6d9dc72194e4f8f70c862493b94ad\buildconfig\config.py", line 210, in main
        deps = CFG.main(**kwds)
      File "C:\Users\myname\AppData\Local\Temp\pip-install-qbgs41e9\pygame_72a6d9dc72194e4f8f70c862493b94ad\buildconfig\config_win.py", line 576, in main
        and download_win_prebuilt.ask(**download_kwargs):
      File "C:\Users\myname\AppData\Local\Temp\pip-install-qbgs41e9\pygame_72a6d9dc72194e4f8f70c862493b94ad\buildconfig\download_win_prebuilt.py", line 302, in ask
        reply = raw_input(
    EOFError: EOF when reading a line
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
How can i solve?
Thanks

**Comment by goshawk22** [comment]
I don't think Windows OS is currently supported by this project.
You'll have to use a linux distro like Ubuntu for it to work.
